### ISSUE TITLE
Master is broken

### ISSUE THREAD

**Issue by andheiberg** [chrisakers/Xdebug-Trace-Visualizer#3]
![](https://www.dropbox.com/s/ly61pic2o29xqy5/Screenshot%202017-03-28%2017.23.34.png?dl=1)

Seems the project no longer works :(

**Comment by andheiberg** [comment]
I tried changing the offending line in index.html:148 to:

```
if (call !== undefined && lines[i-4]) {
      call.setEnd(lines[i-4].split('\t'));
      calls.push(call);
}
```
I basically assumed without look into it really that this is a buffer overrun. But this gives me a strange graph.

![](https://www.dropbox.com/s/1fnclzz2s0gcwyw/Screenshot%202017-03-28%2017.29.27.png?dl=1)

Notice how the end has empty spots.

**Comment by chrisakers** [comment]
Thanks for the report, @AndreasHeiberg. Can you share the trace file in question?

**Comment by chrisakers** [comment]
Closing. This is working as expected with my example trace files. If this is still an issue please provide a trace file that exhibits the issue. Thanks!
